# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

variables:
  - group: global-variables-lds
  - name: solution
    value: '**/*.sln'
  - name: vmImage
    value: 'ubuntu-latest'
  - name: webProjectName
    value: 'LHDS.AdminPortal.Web'
  - name: ConnectionStrings.DefaultConnection
    value: 'Server=localhost,1433;Database=LHDS-Acceptance-$(Build.BuildId);User Id=sa;Password=1Password;TrustServerCertificate=true'

pool: selfhosted-vmss-linux-lds-dev

workspace:
  clean: all

steps:  
  - task: FileTransform@1
    displayName: "Transform AppSettings for CI"
    inputs:
      folderPath: '$(System.DefaultWorkingDirectory)'
      fileType: 'json'
      targetFiles: |
        LHDS.AdminPortal.Api/appsettings.ContinuousIntegration.json
        LHDS.Core.Tests.Acceptance/appsettings.ContinuousIntegration.json
        LHDS.ConfigImportExportTool.Tests.Acceptance/appsettings.ContinuousIntegration.json

  - task: Bash@3
    displayName: "Show AppSettings for CI"
    inputs:
      targetType: 'inline'
      script: |
        cat LHDS.AdminPortal.Api/appsettings.ContinuousIntegration.json
        cat LHDS.Core.Tests.Acceptance/appsettings.ContinuousIntegration.json
        cat LHDS.ConfigImportExportTool.Tests.Acceptance/appsettings.ContinuousIntegration.json

  - task: AzureCLI@2
    displayName: "Add Service Connection to Environment"
    inputs:
      azureSubscription: '$(azureServiceConnectionDev)'
      scriptType: pscore
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        echo "##vso[task.setvariable variable=ServicePrincipalId;]$env:servicePrincipalId"
        echo "##vso[task.setvariable variable=ServicePrincipalKey;]$env:servicePrincipalKey"
        echo "##vso[task.setvariable variable=TenantId;]$env:tenantId"

  - task: Bash@3
    enabled: true
    displayName: Azure Login
    inputs:
      targetType: inline
      script: |
        az login --service-principal --username $(ServicePrincipalId) --password $(ServicePrincipalKey)  --tenant $(TenantId)
        az account set --subscription "ISL-RandD"
        az account show --output table

  - task: UseDotNet@2
    displayName: "Install .NET Core SDK"
    inputs:
      version: 9.x
      performMultiLevelLookup: true
      includePreviewVersions: true # Required for preview versions

  - task: UseNode@1
    displayName: "Install Node.js"
    inputs:
      version: 22.x
      checkLatest: true

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Restore"
    inputs:
      command: "restore"
      feedsToUse: "select"
      projects: "**/*.csproj"
      includeNuGetOrg: true

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Build with Warnings as Errors"
    inputs:
      command: "build"
      projects: "**/*.csproj"
      arguments: "--warnaserror"

  - task: DotNetCoreCLI@2
    displayName: C# Unit Tests
    inputs:
      command: 'test'
      projects: '**/*.Tests.Unit.csproj'

  - task: Bash@3
    enabled: true
    displayName: Install Docker
    inputs:
      targetType: inline
      script: >-
        sudo apt update
          
        sudo apt install apt-transport-https ca-certificates curl
        software-properties-common -y
        
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo
        apt-key add -
        
        sudo add-apt-repository "deb [arch=amd64]
        https://download.docker.com/linux/ubuntu bionic stable"
        
        sudo apt update
        
        apt-cache policy docker-ce
        
        sudo apt install docker-ce -y
        
        sudo systemctl start docker

  - task: Bash@3
    enabled: true
    displayName: Pulling Required Docker Images for SQL Server
    inputs:
      targetType: inline
      script: |-
        sudo docker stop sql1

        sudo docker rm sql1

        sudo docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=1Password" \
            -p 1433:1433 --name sql1 --hostname sql1 \
            -d \
            mcr.microsoft.com/mssql/server:2022-latest
            
  - task: Bash@3
    enabled: true
    displayName: Docker SQL Connection Test
    inputs:
      targetType: inline
      script: |
        CONTAINER_NAME="sql1"
        # Set the maximum number of retries
        MAX_RETRIES=10
        # Set the retry interval in seconds
        RETRY_INTERVAL=5
        # Initialize the retry counter
        RETRY_COUNT=0
        
        while [[ $RETRY_COUNT -lt $MAX_RETRIES ]]; do
        
          # Check if the SQL container is running
          container_status=$(sudo docker inspect -f '{{.State.Status}}' $CONTAINER_NAME)
        
          if [[ $container_status != "running" ]]; then
            # The SQL container is not running
            echo "SQL Server container is not running. Retrying...(retry $RETRY_COUNT/$MAX_RETRIES)"
            sleep $RETRY_INTERVAL
            ((RETRY_COUNT++))
            continue
          fi
        
          # The SQL container is running
        
          # Wait for the SQL container to be ready
          if [[ "$(sudo docker logs $CONTAINER_NAME | grep 'SQL Server is now ready for client connections' | wc -l)" -eq 0 ]]; then
            echo "Waiting for SQL Server log entry stating its ready for connections...(retry $RETRY_COUNT/$MAX_RETRIES)"
            sleep $RETRY_INTERVAL
            ((RETRY_COUNT++))
          else
            # The SQL container is ready
            echo "SQL Server container is ready!"
            break
          fi
        
        done
        
        # If the retry counter is equal to the maximum number of retries, then the container failed to start
        if [[ $RETRY_COUNT -eq $MAX_RETRIES ]]; then
          echo "SQL Server container is not ready after $MAX_RETRIES retries"
          exit 1
        fi
        
  - task: DotNetCoreCLI@2
    displayName: C# Acceptance Tests
    inputs: 
      command: 'test'
      projects: '**/*.Tests.Acceptance.csproj'
      arguments: '--environment ASPNETCORE_ENVIRONMENT=ContinuousIntegration'
      envVars: 'ASPNETCORE_ENVIRONMENT=ContinuousIntegration'
      environmentVariables: |
        MESHCONFIGURATION__MAILBOXID=$(MESHCONFIGURATION__MAILBOXID)
        MESHCONFIGURATION__PASSWORD=$(MESHCONFIGURATION__PASSWORD)
        MESHCONFIGURATION__KEY=$(MESHCONFIGURATION__KEY)
        MESHCONFIGURATION__ROOTCERTIFICATE=$(MESHCONFIGURATION__ROOTCERTIFICATE)
        MESHCONFIGURATION__INTERMEDIATECERTIFICATES__0=$(MESHCONFIGURATION__INTERMEDIATECERTIFICATES__0)
        MESHCONFIGURATION__CLIENTCERTIFICATE=$(MESHCONFIGURATION__CLIENTCERTIFICATE)
        CRYPTOGRAPHY__PRIVATEKEY=$(CRYPTOGRAPHY__PRIVATEKEY)
        CRYPTOGRAPHY__PUBLICKEY=$(CRYPTOGRAPHY__PUBLICKEY)
        CRYPTOGRAPHY__PASSPHRASE=$(CRYPTOGRAPHY__PASSPHRASE)
        FTPDOWNLOAD__FTPSERVER=$(FTPDOWNLOAD__FTPSERVER)
        FTPDOWNLOAD__FTPPORT=$(FTPDOWNLOAD__FTPPORT)
        FTPDOWNLOAD__FTPPASSWORD=$(FTPDOWNLOAD__FTPPASSWORD)
        FTPDOWNLOAD__FTPUSERNAME=$(FTPDOWNLOAD__FTPUSERNAME)
        FTPDOWNLOAD__FTPKEY=$(FTPDOWNLOAD__FTPKEY)
        FTPDOWNLOAD__FTPPASSPHRASE=$(FTPDOWNLOAD__FTPPASSPHRASE)
        ONTOLOGYSETTINGS__TERMINOLOGYSERVERAUTHENTICATIONRELATIVEURL=$(ONTOLOGYSETTINGS__TERMINOLOGYSERVERAUTHENTICATIONRELATIVEURL)
        ONTOLOGYSETTINGS__TERMINOLOGYSERVERRESOURCERELATIVEURL=$(ONTOLOGYSETTINGS__TERMINOLOGYSERVERRESOURCERELATIVEURL)
        ONTOLOGYSETTINGS__CLIENTID=$(ONTOLOGYSETTINGS__CLIENTID)
        ONTOLOGYSETTINGS__CLIENTSECRET=$(ONTOLOGYSETTINGS__CLIENTSECRET)

  - task: Npm@1
    displayName: NPM Install
    inputs:
      workingDir: '$(webProjectName)/ClientApp'
      command: 'install'

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Build (API)"
    inputs:
      command: 'build'
      projects: '**/LHDS.AdminPortal.Api.csproj'
      arguments: --output $(System.DefaultWorkingDirectory)/publish_output_website_api --configuration Release

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Build (Frontend)"
    inputs:
      command: 'build'
      projects: '**/LHDS.AdminPortal.Web.csproj'
      arguments: --output $(System.DefaultWorkingDirectory)/publish_output_website_frontend --configuration Release

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Build (EMIS Landing Function)"
    inputs:
      command: 'build'
      projects: '**/LHDS.Functions.Landings.Emis.csproj'
      arguments: --output $(System.DefaultWorkingDirectory)/publish_output_emis_func --configuration Release

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Build (Opt-Out Function)"
    inputs:
      command: 'build'
      projects: '**/LHDS.Functions.OptOut.csproj'
      arguments: --output $(System.DefaultWorkingDirectory)/publish_output_optout_func --configuration Release

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Build (PDS Function)"
    inputs:
      command: 'build'
      projects: '**/LHDS.Functions.Pds.csproj'
      arguments: --output $(System.DefaultWorkingDirectory)/publish_output_pds_func --configuration Release
  
  - task: DotNetCoreCLI@2
    displayName: "Dotnet Build (Tpp Function)"
    inputs:
      command: 'build'
      projects: '**/LHDS.Functions.Landings.Tpp.csproj'
      arguments: --output $(System.DefaultWorkingDirectory)/publish_output_tpp_func --configuration Release

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Build (Addresses Function)"
    inputs:
      command: 'build'
      projects: '**/LHDS.Functions.Addresses.csproj'
      arguments: --output $(System.DefaultWorkingDirectory)/publish_output_addresses_func --configuration Release

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Build (Terminology Function)"
    inputs:
      command: 'build'
      projects: '**/LHDS.Functions.Terminology.csproj'
      arguments: --output $(System.DefaultWorkingDirectory)/publish_output_terminology_func --configuration Release
      
  - task: Npm@1 
    displayName: Run Code linting
    inputs:
      command: 'custom'
      workingDir: $(webProjectName)/ClientApp
      customCommand: 'run lint'

  #- task: Npm@1
  #  displayName: Client Tests
  #  inputs:
  #    command: 'custom'
  #    workingDir: $(webProjectName)/ClientApp
  #    customCommand: 'run test:ci'    

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Publish Frontend (Development)"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "**/LHDS.AdminPortal.Web.csproj"
      arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_development_frontend_website --configuration Development"
      zipAfterPublish: true
      modifyOutputPath: false

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Publish Frontend (idev)"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "**/LHDS.AdminPortal.Web.csproj"
      arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_idev_frontend_website --configuration idev"
      zipAfterPublish: true
      modifyOutputPath: false

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Publish Frontend (odev)"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "**/LHDS.AdminPortal.Web.csproj"
      arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_odev_frontend_website --configuration odev"
      zipAfterPublish: true
      modifyOutputPath: false

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Publish Frontend (Test)"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "**/LHDS.AdminPortal.Web.csproj"
      arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_test_frontend_website --configuration Test"
      zipAfterPublish: true
      modifyOutputPath: false

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Publish Frontend (PreProduction)"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "**/LHDS.AdminPortal.Web.csproj"
      arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_preproduction_frontend_website --configuration PreProduction"
      zipAfterPublish: true
      modifyOutputPath: false

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Publish Frontend (Production)"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "**/LHDS.AdminPortal.Web.csproj"
      arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_production_frontend_website --configuration Production"
      zipAfterPublish: true
      modifyOutputPath: false

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Publish API"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "**/LHDS.AdminPortal.Api.csproj"
      arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_api_website --configuration Release"
      zipAfterPublish: true
      modifyOutputPath: false

  - task: ArchiveFiles@2
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
    displayName: 'Archive files - Emis Function'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output_emis_func'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_emis_func.zip
      replaceExistingArchive: true

  - task: ArchiveFiles@2
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: 'Archive files - OptOut Function'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output_optout_func'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_optout_func.zip
      replaceExistingArchive: true

  - task: ArchiveFiles@2
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: 'Archive files - Pds Function'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output_pds_func'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_pds_func.zip
      replaceExistingArchive: true

  - task: ArchiveFiles@2
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
    displayName: 'Archive files - Tpp Function'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output_tpp_func'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_tpp_func.zip
      replaceExistingArchive: true

  - task: ArchiveFiles@2
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
    displayName: 'Archive files - Addresses Function'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output_addresses_func'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_addresses_func.zip
      replaceExistingArchive: true

  - task: ArchiveFiles@2
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
    displayName: 'Archive files - Terminology Function'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output_terminology_func'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_terminology_func.zip
      replaceExistingArchive: true

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_api_website
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
    displayName: 'Publish Artifact - API'
    artifact: drop-api

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_development_frontend_website
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
    displayName: 'Publish Artifact - Frontend (Development)'
    artifact: drop-frontend-development

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_idev_frontend_website
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
    displayName: 'Publish Artifact - Frontend (idev)'
    artifact: drop-frontend-idev

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_odev_frontend_website
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
    displayName: 'Publish Artifact - Frontend (odev)'
    artifact: drop-frontend-odev

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_test_frontend_website
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
    displayName: 'Publish Artifact - Frontend (Test)'
    artifact: drop-frontend-test

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_preproduction_frontend_website
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
    displayName: 'Publish Artifact - Frontend (PreProduction)'
    artifact: drop-frontend-preproduction

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_production_frontend_website
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
    displayName: 'Publish Artifact - Frontend (Production)'
    artifact: drop-frontend-production

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_emis_func.zip
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
    displayName: 'Publish Artifact - Emis Function'
    artifact: drop-emis-func

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_optout_func.zip
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: 'Publish Artifact - Opt-Out Function'
    artifact: drop-optout-func

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_pds_func.zip
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: 'Publish Artifact - PDS Function'
    artifact: drop-pds-func

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_tpp_func.zip
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
    displayName: 'Publish Artifact - Tpp Function'
    artifact: drop-tpp-func

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_addresses_func.zip
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
    displayName: 'Publish Artifact - Addresses Function'
    artifact: drop-addresses-func

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_terminology_func.zip
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
    displayName: 'Publish Artifact - Terminology Function'
    artifact: drop-terminology-func
