# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

variables:
  solution: '**/*.sln'
  # Agent VM image name
  vmImage: ubuntu-latest
  webProjectName: 'LHDS.AdminPortal.Web'

steps:
  - task: UseDotNet@2
    displayName: "Install .NET Core SDK"
    inputs:
      version: 7.x
      performMultiLevelLookup: true
      includePreviewVersions: true # Required for preview versions

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Restore"
    inputs:
      command: "restore"
      feedsToUse: "select"
      projects: "**/*.csproj"
      includeNuGetOrg: true

 # - task: DotNetCoreCLI@2
 #   displayName: "Dotnet Build"
 #   inputs:
 #     command: 'build'
 #     projects: '**/*.csproj'
 #     arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Build (EMIS Download)"
    inputs:
      command: 'build'
      projects: '**/LHDS.Functions.Landings.Emis.csproj'
      arguments: --output $(System.DefaultWorkingDirectory)/publish_output_emis_func --configuration Release

  - task: DotNetCoreCLI@2
    displayName: Run Unit Tests
    inputs:
      command: 'test'
      projects: '**/*.Tests.Unit.csproj'

- task: Npm@1
    displayName: NPM Install
    inputs:
      workingDir: '$(webProjectName)/ClientApp'
      command: 'install'

  #- task: DotNetCoreCLI@2
  #  displayName: Acceptance Tests
  #  inputs:
  #    command: 'test'
  #    projects: '**/*.Tests.Acceptance.csproj'

  - task: Npm@1 
    displayName: Run code linting
    inputs:
      command: 'custom'
      workingDir: $(webProjectName)/ClientApp
      customCommand: 'run lint'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output_emis_func'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_emis_func.zip
      replaceExistingArchive: true

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_emis_func.zip
    artifact: drop