# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

variables:
  solution: '**/*.sln'
  # Agent VM image name
  vmImage: ubuntu-latest
  webProjectName: 'LHDS.AdminPortal.Web'

steps:
  - task: UseDotNet@2
    displayName: "Install .NET Core SDK"
    inputs:
      version: 7.x
      performMultiLevelLookup: true
      includePreviewVersions: true # Required for preview versions

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Restore"
    inputs:
      command: "restore"
      feedsToUse: "select"
      projects: "**/*.csproj"
      includeNuGetOrg: true

  - task: Npm@1
    displayName: NPM Install
    inputs:
      workingDir: '$(webProjectName)/ClientApp'
      command: 'install'

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Build"
    inputs:
      command: 'build'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Build (EMIS Download)"
    inputs:
      command: 'build'
      projects: '**/LHDS.Functions.Landings.Emis.csproj'
      arguments: --output $(System.DefaultWorkingDirectory)/publish_output_emis_func --configuration Release

  - task: DotNetCoreCLI@2
    displayName: C# Unit Tests
    inputs:
      command: 'test'
      projects: '**/*.Tests.Unit.csproj'

  #- task: DotNetCoreCLI@2
  #  displayName: C# Acceptance Tests
  #  inputs:
  #    command: 'test'
  #    projects: '**/*.Tests.Acceptance.csproj'
  
  #- task: DotNetCoreCLI@2
  #  displayName: C# Integration Tests
  #  inputs:
  #    command: 'test'
  #    projects: '**/*.Tests.Integration.*.csproj'
      
  - task: Npm@1 
    displayName: Run Code linting
    inputs:
      command: 'custom'
      workingDir: $(webProjectName)/ClientApp
      customCommand: 'run lint'

  #- task: Npm@1
  #  displayName: Client Tests
  #  inputs:
  #    command: 'custom'
  #    workingDir: $(webProjectName)/ClientApp
  #    customCommand: 'run test:ci'    

  #- task: DotNetCoreCLI@2
  #  displayName: "Dotnet Publish (Debug)"
  #  condition: ne(variables['Build.Reason'], 'PullRequest')
  #  inputs:
  #    command: "publish"
  #    publishWebProjects: true
  #    projects: "**/*.csproj"
  #    arguments: "-o $(Build.ArtifactStagingDirectory)/debug --configuration Debug"
  #    zipAfterPublish: true
  #    modifyOutputPath: true
 
  #- task: DotNetCoreCLI@2
  #  displayName: "Dotnet Publish (Acceptance)"
  #  condition: ne(variables['Build.Reason'], 'PullRequest')
  #  inputs:
  #    command: "publish"
  #    publishWebProjects: true
  #    projects: "**/*.csproj"
  #    arguments: "-o $(Build.ArtifactStagingDirectory)/acceptance --configuration Acceptance"
  #    zipAfterPublish: true
  #    modifyOutputPath: true

  #- task: DotNetCoreCLI@2
  #  displayName: "Dotnet Publish (Release)"
  #  condition: ne(variables['Build.Reason'], 'PullRequest')
  #  inputs:
  #    command: "publish"
  #    publishWebProjects: true
  #    projects: "**/*.csproj"
  #    arguments: "-o $(Build.ArtifactStagingDirectory)/release --configuration Release"
  #    zipAfterPublish: true
  #    modifyOutputPath: true

  #- task: PublishBuildArtifacts@1
  #  displayName: "Publish Build Artifacts"
  #  condition: ne(variables['Build.Reason'], 'PullRequest')
  #  inputs:
  #    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  #    ArtifactName: 'drop'
  #    publishLocation: 'Container'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output_emis_func'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_emis_func.zip
      replaceExistingArchive: true

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_emis_func.zip
    artifact: drop
