// <auto-generated />
using System;
using LHDS.Core.Brokers.Storages.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LHDS.Core.Migrations
{
    [DbContext(typeof(StorageBroker))]
    [Migration("20230825114437_UpdatedDataSetAndChildConfigurations")]
    partial class UpdatedDataSetAndChildConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LHDS.Core.Models.Foundations.Audits.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("IngestionTrackingId")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IngestionTrackingId");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.ColumnDefinitions.ObjectColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColumnDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DataTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DatasetObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FhirDataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAuthorCode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleteFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEntityBusinessKey")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMutable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPersonConfidentialData")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecordBusinessKey")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSenderCode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSensitiveRecordMarker")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSequencing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWatermark")
                        .HasColumnType("bit");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<string>("MaskingMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdinalPosition")
                        .HasColumnType("int");

                    b.Property<string>("OurColumnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartitionColumnLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("PopulatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Precision")
                        .HasColumnType("int");

                    b.Property<int?>("Scale")
                        .HasColumnType("int");

                    b.Property<string>("SqlDataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierColumnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierDateFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfPersonConfidentialData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DatasetObjectId");

                    b.ToTable("ColumnDefinitions");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ColumnDefinitionsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.DataSetObjects.DataSetObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DataSetSpecificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeletionHandling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterchangeProtocol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSubmissionHeaderObject")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTransactionLog")
                        .HasColumnType("bit");

                    b.Property<string>("ObjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OurObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("PushOrPull")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DataSetSpecificationId");

                    b.ToTable("DatasetObjects");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("DatasetObjectsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.DataSets.DataSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ActiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ActiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DataSetAliasses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSetAuthor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSourceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Datasets");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("DatasetsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.DataSets.DataSetSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ActiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ActiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DataSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateImplemented")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateReleased")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateSuperceeded")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntityChangeSynchronisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMultiSender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OurSpecificationVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("PreceededBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuperseededBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierSpecificationVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DataSetId");

                    b.ToTable("DatasetSpecifications");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("DatasetSpecificationsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.DataTypes.DataType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("DataTypes");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("DataTypesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.IngestionTrackings.IngestionTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Decrypted")
                        .HasColumnType("bit");

                    b.Property<string>("DecryptedFileName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DecryptedFileSize")
                        .HasColumnType("int");

                    b.Property<string>("EncryptedFileName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EncryptedFileSize")
                        .HasColumnType("int");

                    b.Property<bool>("FileDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("IngestionTrackings");
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.OptOuts.OptOut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BatchReference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CacheTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSentToMesh")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NhsNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UniqueReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("OptOuts");
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.PdsAudits.PdsAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("PdsAudits");
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.Suppliers.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DecryptionManualTriggerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LandingManualTriggerUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67680f17-9d0c-4474-8b35-56ca8f9df1f6"),
                            CreatedBy = "System",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 8, 25, 11, 44, 37, 617, DateTimeKind.Unspecified).AddTicks(5312), new TimeSpan(0, 0, 0, 0, 0)),
                            DecryptionManualTriggerUrl = "Update this => environment specific",
                            Description = "Emis Supplier",
                            FriendlyName = "EMIS",
                            LandingManualTriggerUrl = "Update this => environment specific",
                            Name = "EMIS",
                            UpdatedBy = "System",
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 8, 25, 11, 44, 37, 617, DateTimeKind.Unspecified).AddTicks(5324), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.Audits.Audit", b =>
                {
                    b.HasOne("LHDS.Core.Models.Foundations.IngestionTrackings.IngestionTracking", "IngestionTracking")
                        .WithMany("Audits")
                        .HasForeignKey("IngestionTrackingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("IngestionTracking");
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.ColumnDefinitions.ObjectColumn", b =>
                {
                    b.HasOne("LHDS.Core.Models.Foundations.DataSetObjects.DataSetObject", "DatasetObject")
                        .WithMany("DataSetObjects")
                        .HasForeignKey("DatasetObjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DatasetObject");
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.DataSetObjects.DataSetObject", b =>
                {
                    b.HasOne("LHDS.Core.Models.Foundations.DataSets.DataSetSpecification", "DataSetSpecification")
                        .WithMany("DataSetObjects")
                        .HasForeignKey("DataSetSpecificationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DataSetSpecification");
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.DataSets.DataSetSpecification", b =>
                {
                    b.HasOne("LHDS.Core.Models.Foundations.DataSets.DataSet", "DataSet")
                        .WithMany("DatasetSpecifications")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.IngestionTrackings.IngestionTracking", b =>
                {
                    b.HasOne("LHDS.Core.Models.Foundations.Suppliers.Supplier", "Supplier")
                        .WithMany("IngestionTrackings")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.DataSetObjects.DataSetObject", b =>
                {
                    b.Navigation("DataSetObjects");
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.DataSets.DataSet", b =>
                {
                    b.Navigation("DatasetSpecifications");
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.DataSets.DataSetSpecification", b =>
                {
                    b.Navigation("DataSetObjects");
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.IngestionTrackings.IngestionTracking", b =>
                {
                    b.Navigation("Audits");
                });

            modelBuilder.Entity("LHDS.Core.Models.Foundations.Suppliers.Supplier", b =>
                {
                    b.Navigation("IngestionTrackings");
                });
#pragma warning restore 612, 618
        }
    }
}
